### ISSUE TITLE
Create integration test for reliability 

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#235]
# Task Description
Currently, we haven't really validated the guaranteed reliabity yet. We do have unit tests but it would be nice to see an integration test that uploads a 10..50MB file to another endpoint where after it validates the transferred file. 

We already have a test environment set up in `/bin` which can be used for this purpose.

# Task TODO
- [ ] Add file transfer test [here](https://github.com/amethyst/laminar/blob/master/src/bin/laminar-tester.rs#L152)
- [ ] Create similar function as [this one](https://github.com/amethyst/laminar/blob/master/src/bin/laminar-tester.rs#L165)
- [ ] Make sure the file get's validated on the [server](https://github.com/amethyst/laminar/blob/master/src/bin/laminar-tester.rs#L123)
