### ISSUE TITLE
Milestone 0.1.0

### ISSUE THREAD

**Issue by TimonPost** [amethyst/laminar#58]
This is the milestone we need to do before releasing laminar 0.1.0.

- [x] Congestion avoidance (issue #3).
     - [x] We now have an estimation of the RTT time (PR #30). 
     - The real congestion avoidance will be done at a higher level may be in `amtehyst_network`.
- [x] Protocol Id, (issue: #4, PR, #55) 
- [x] Fragmentation (#1)
- [x] Acknowlegement system.
- [x] Examples (PR #6, PR #5)
- [x] Virtual Connections connections.
     - [x]  Implemented virtualconnections ( PR #20).
     - [x] Issue #32 still needs to be done.
- [ ] Different reliablities
   We need away to devide different procesess packets with differenbt reliablilitie options.
   - [x] Packet header implementation to support different reliablities (PR #42).  
   - [ ] Process different reliablities when packet is received (issue: #39, #65 )
- [ ] Testing
  - [ ] Add scenario tests (issue #10)
  - [x] Integration tests (PR #19) 
- [ ] Md Book (issue #33)
  - [x] Proof of concept
  - [ ] Still needs to be updated alot e.g. grammar, more information etc.  

If all of the above are implemented we are ready for 0.1.0 release. Feel free to add more if I forgot some.

**Comment by LucioFranco** [comment]
closing this in favor of using the milestone.
